# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azctx < Formula
  desc "Switch faster between subscriptions in your azure cli."
  homepage "https://githubs.com/whiteducksoftware/azctx"
  version "2023.08.1"
  license "MIT"

  depends_on "azure-cli"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/whiteducksoftware/azctx/releases/download/2023.08.1/azctx_darwin_arm64.zip"
      sha256 "9c5dc94452a1af502a9740abd54e492788b475baa1637c4c55a0d0b1498011e9"

      def install
        bin.install "azctx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/whiteducksoftware/azctx/releases/download/2023.08.1/azctx_darwin_amd64.zip"
      sha256 "7b18d26956b969827e57b0b0b72a232d21b9adb683d185c941ab408e95cf7c92"

      def install
        bin.install "azctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/whiteducksoftware/azctx/releases/download/2023.08.1/azctx_linux_armv6.zip"
      sha256 "49dda3f8900461dfa8898704848d36c0eaea9b568aa4b0293c7e8ac33d72b6d5"

      def install
        bin.install "azctx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/whiteducksoftware/azctx/releases/download/2023.08.1/azctx_linux_amd64.zip"
      sha256 "da152237491a52759e8de1dc2679e1779073863c1ba43fabb51e98eca3c39c6c"

      def install
        bin.install "azctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/whiteducksoftware/azctx/releases/download/2023.08.1/azctx_linux_arm64.zip"
      sha256 "fc875b243f9346ae5d9ad7ed8d3cc8066fff11b033e8ca22a7a49ac71bd90b10"

      def install
        bin.install "azctx"
      end
    end
  end
end
